apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: algospectra-sops
    namespace: argocd
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:AnNDUCSotvgLktTXXos=,iv:QOGs72gBjip36FT9e3AcDjg0ErUd3d30+eufEAsx+DA=,tag:sEIwTFxO6TZPwuh4cZx6ag==,type:str]
          labels:
            argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:IDZWHIC+Jld1KQ==,iv:OL5hreUm33V9msLjs+rCXk1EKfS4sJYKF7AgeBZ7dZ4=,tag:SIOThwCvKcM/eb2Bt+3Fqw==,type:str]
          stringData:
            url: ENC[AES256_GCM,data:CwMFlq/KtVMWsZsN3uX34yc3fHH+n81IfutpNpEFfwEesgH2wdHNoVw=,iv:+KKwfC7PsQsuk3dc09I240SZZb//KkyzRa42QozCOTQ=,tag:VqfvrsHjDJPJvrZBfgEuOA==,type:str]
            sshPrivateKey: ENC[AES256_GCM,data:eXf8Rx4NfI5WSNR8qRTKCFVrg6P94AG8ndo3FzD+/tHojddBfeE/vGMyQoL7tGD2XJOrm5BBJq7/dPNClKw1Pg6T1FPj1ocEfvc9RYH1fSFnPYsOhYVdjc69Ndpt+brZDJs8paXWT9RZNKayaArXgr8+8xqE2ONgTxrUX4J7mOGqENfBuxw7F1wWuMz6RxsHgCI5MJovE/zn6PHnNSx0RpD0++b4vSguNI/IgaIVZVXW9rckyR9OYoDaAAi6gWlDiFC69ijcyazwRguYgr/2FBrmAagWg92xZMK87tkg6utyDvrXk1c1bUi+X4WQN/ulbtgbg2Jea4cUT5vv4yRJT5uyK8QeKRCBHIbbDlSA2hd2eUV2NQ4MgYmXGPVn4glDjrzeGn+2USgaMMP6o5NMOudDGjsz+BcE7xUG/BEGFqUqBCI+TMl33ALqXSb6LvwAtDr+evoiGhqwCOcvmtkj8TCuInb47FWUs3A0q2duA/ezSuuuVbdmKHksBM+dXB+/E2qZwE87b4OFED6PUHmBQ8kieMC+sNt9qGGU+svCEGmsm8E=,iv:UBaOUOgkhw6GXU4qlIybNUumcuFaZtLJQbooTC/4yVw=,tag:29V9u90+LHcHLviM12niqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSXJHbDFHeHN0dE1RSmtI
            V2hWRXVzRnpaNVNLOVN1dDdCeEhpaVRpcVMwCnZzQmV4NmR1S201UU9vWm9idVg4
            M2JQT3VnYkMxenJZMXRFM1lKN01JVmsKLS0tIGFSaFF2R3VKWkNqVjBGNURxS29m
            R3VSb29sQWhDYUxGWGxQUHBBTU4wTUEKkNT550fWfpgDeEH/yH5pYGoizfZOrfx9
            aZyZndHkiOki7NonWTW5ZngUK1/oJofqYRlM77Br/0/3Vum2ErCB+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-05T17:56:43Z"
    mac: ENC[AES256_GCM,data:x5rApb6roojfe/G6g+ZNVaP4xlY/7uttHmhpe0xIsNLPyFTsJYVEXjJO2X+31l7FsplribUi0h4yCj6pK2hEzdY6o6TjFOBBV0gr0EDJCElBK/glWAR7uvKTgmH3TDfUqgNZRn7N+yobsPh3fd32aXpWpXmtdvR3bvQ0AJPHe78=,iv:7FBuQjYw17Fqrljl9nXSbt//HfI6Aj4P1WLpHdHynUQ=,tag:Z4U/GZPvZbm3iqf7U95kPA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
