apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: algospectra
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Algospectra/kubernetes.git
    path: main
    # directory
    directory:
      recurse: true

