apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  project: default
  sources:
    - chart: gha-runner-scale-set-controller
      repoURL: https://actions-runner-controller.github.io/actions-runner-controller
      targetRevision: 0.9.3
    - chart: gha-runner-scale-set
      repoURL: https://actions-runner-controller.github.io/actions-runner-controller
      targetRevision: 0.9.3
      helm:
        values: |
          # Values specific to the Actions Runner Controller Helm chart
          githubConfigSecret: github-pat
          githubConfigUrl: https://github.com/hnatekmarorg
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
