apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
    targetRevision: main
    helm:
      chart: gha-runner-scale-set-controller
      releaseName: arc
      namespace: arc-systems
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller-algovectra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
    targetRevision: main
    helm:
      chart: gha-runner-scale-set
      releaseName: arc-algovectra
      namespace: arc-systems
      values: |
        # Values specific to the Actions Runner Controller Helm chart
        githubConfigSecret: github-pat
        githubConfigUrl: https://github.com/Algovectra
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller-hnatekmar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
    targetRevision: main
    helm:
      chart: gha-runner-scale-set
      releaseName: arc-hnatekmar
      namespace: arc-systems
      values: |
        # Values specific to the Actions Runner Controller Helm chart
        githubConfigSecret: github-pat
        githubConfigUrl: https://github.com/hnatekmarorg
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
