apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm

    targetRevision: 0.41.11
    helm:
      releaseName: argo-workflows
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-workflows