apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: woodpecker
    namespace: woodpecker
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:IqNuCVQY7YqGH3VCT/V34fBEyI4qp3cn,iv:35++iRN9c2JlNtmOBV/11K9pYyWivazXh8PJYQ1sqpg=,tag:nXC+G2oEmohdEn2g3Q3Oag==,type:str]
          stringData:
            WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:yB13mh3BUBmtxwp1A2/X3oT6VO0=,iv:H2jsbroCpMUsm+3ZwXkajYyGOGhCb+Nk8T0gfnyKGns=,tag:AkvSA/ZlpfiZd3P1lSsLDQ==,type:str]
            WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:d6NQ2cIS7JfgDRDhjqZISKpLINNLDPq6lvUpm05klM8hS+K95G/EkQ==,iv:aUb9mNxMruUdYU3VsijSkuuT2IuPIB4Z2kgtRJme14s=,tag:sfq1B6/Lj35Y4A3oF438zA==,type:str]
        - name: ENC[AES256_GCM,data:4bPLO6jDIWVZAUE+o7ZMbQ==,iv:D5AJ8j34zwvGOxOkYfij9eFDvJycIorp56HgCtKcOSE=,tag:i059Zdi+PsVbIqDo4IH4iQ==,type:str]
          stringData:
            WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:FaJoqrtZJ38U3M58RFdHi5IIhXorbyQuYUvGvCCPYasOKR0YRZPcHc2Mx6XClAOkEp0XLVeS8pC+W+BHArsbYQ==,iv:NlF5B4d8iHsU80m+dMcB433q7AbTafMrLNRyeByFPvg=,tag:jNLiPo6WCuZ6IFKqFOaSxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYkMyejhtVXd3QVQzMUJ0
            VmVUMzUzWEN5cGsrbUlxU0kwQnhoQjZ5bUhnCnhQY0oweTZZYThRRGJTYkJGNEta
            UU9NMm1nUXNTa1djTW10Q3dNQjZiaDQKLS0tIFFMY2dibWFKYk10ZG5WWVFLTDVT
            NkhtUVZFWXc0bk9tUS9mZ3dOZlFrZHcKZIM2hfuwXFgCAgcu4R3etP9DDB17AM3r
            u2EwWWbm0YkjyNhuZhVEUXj66Yv84iWm7gX2X+c8VDowNB5g05X9Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T08:16:19Z"
    mac: ENC[AES256_GCM,data:skv/AQFUC+hDQVeFeu1spi8DbE2EdKfMWP6f/D9MdoQdFRJ6oYMxJRumpFlg1XqydW0f4ouhrIu/s3hou2Mm19vqAKBi7Q8BiVVIoU6IY/TZQyQGmi0HSFbKB1nPwxYZ6TwvtjiZ8HtAV22tnVF7WE38WrdZT+7tALhEIcF34p8=,iv:FKhG3AoK+0GjhpckyRAJNcwXYXS2xxEbSEKDdKfNOGc=,tag:MU9C2BiY9+jQUJG6tJG2rQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
