apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: influx-secret
    namespace: influx
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:B4+9udtwnG65ViQDxQ==,iv:b1/9GQ62FvWpWOROBf3dkBwOY1PNTiNKyq/F0NLkEyc=,tag:hRK/Zuv4k5Xc233zNhJyeA==,type:str]
          stringData:
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:4pJn4WR1QxHadqpIm07pW61gqJg=,iv:dIHEg9I9XCUj2rHB/2sxG050jnPDuLRNu6CePh9hwco=,tag:eXGVNU/lNlFdYD1jOcJp9A==,type:str]
            DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:Yymi3ki5HbiPaS1Eg1X319Yyq5s=,iv:CS37fJOdp/4PUJeVBZdhcdxVeALXahuUeatlaBNcKMM=,tag:0e2uLNB35u6iY2tP0gg/Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dmRvOHRINm9lSUsrSkEz
            bUJkOWVGYmNJNVBKeDBwQUlFOEEzREVVdGh3Cm16bFJCMGFZMGZrbFgwTjlmVzZW
            WEpCN2pEMnIyN3hVTDFRUzgyeGo4SncKLS0tIDlPeTBaNFRvblB6RS9ZUFFFcUlp
            dHRwdHRXR2RYUmJuY3RtNllwVU0wb0UKNbqZQppo7IZRo1f3Kn/dPaLvtfgUO4vK
            pp52wpCp5X4IHky88K+dewItlEKmSZ75TGTWkWrXLhoN1X+gQ17Teg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T16:56:32Z"
    mac: ENC[AES256_GCM,data:tmqSTra794aFPMWiet1p8oI4w3pfcvG64mdiG/e3bGndBjBDxN23fbF6gH43HCVJNqlLY5gNuP6r3Q/J4XwekATqpJYhw9S6Ew6ZuNUjFR9sFllh6Gy9jgo4xrL/vSQAjsEZ04tdjyt9UNABaGeikoh5zYdkO1iZ5S5xed2/qIM=,iv:WrdNc5GYzr6onKP+eY+L+OcKplTJjerj+zrlaY/gklw=,tag:qciDW7TUHOYnSsocRc7Q7w==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
