apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
    namespace: argocd
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:AhDpFFSHMaAn8g==,iv:vRqJoT+K4bNrTClwnULX6mePQ6eCap7ezSwcB8f3ohM=,tag:9gf7s0nYi5I/nDRRXNbQiA==,type:str]
          labels:
            app.kubernetes.io/name: ENC[AES256_GCM,data:6m0D7sJXKDSu,iv:LU2VnFVxeIQtfHZrYPVWks6Esed7b5XAWERmEhLV+x4=,tag:fHUXFbP68QXCCthsTe3t2w==,type:str]
            app.kubernetes.io/part-of: ENC[AES256_GCM,data:3bmCTsEQ,iv:sMW1HVwPY4mxIJUfqZ7oONaTkYJA/7Nl0mx1aa6Cb14=,tag:MfX42kJao41Uz/75R6x2JQ==,type:str]
          stringData:
            oidc.authentik.clientID: ENC[AES256_GCM,data:4kNt42GYE+v6yIMOc4LQJicAFcWBvIrPTSbVLz/VSJC5gvprTc/SWA==,iv:nQkDBv6IpkKFJQ+ZV0r9K+J+YmUDaylSMkJluxJ2DlU=,tag:yX4JHdKptCveVssrENDcXA==,type:str]
            oidc.authentik.clientSecret: ENC[AES256_GCM,data:CWA11chpO2WRekicCUoILEPxNYWZ5WLrQxOgiEY//SMO9hqvBCBZUzzUtxc83Xn/4P1CfYQ/fm1f1s+D0xUYUHyBwJfXeXDliQ63G4vfX+gENaDbYl57FrZI5a+1KAuHo3XmQ03sPZT28F4Nga5X1VCtQbGBm/ETTuCZWPZL9HQ=,iv:VLu4aSTwMxUT1+QrBij+VW1QLkEMmpOJa4r8PFqfI/U=,tag:x8mX3+tl/8oF5P/4OXOFXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOUdJMnBNeStiZjdIYnhk
            TFBDZEpLWmlLd0NEWGx4SXhKRGZ5VVpiZzNVCkphcVo4Sm1nZ080a0phNTYwUDJy
            RmIwNjBjWWw4bVk0NUlWeXdzRmU3OWsKLS0tIEV0RkljYTUwUi9xdWtnK3BuRmE2
            bzMzdmJPYzN2OE9tYkUxUXU3WDRJbDQKSeNrgvtFrDqi7i4fKXb/1xtg5ObgEGXE
            30noJBoFtyhF/ucRuu07QTKIam3iq64GH6+DO6sUbgp5a+K9LzttbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:ZeQbi3svxokAYlCbd13HvCI+KIsGFAMv0343lAU77lRnkhp6GWwnVQsu/d0uOsCSPBmh+Gn6M6IU1hX01WiKwmeOCq4eaD8YaL8HOC1qAEo71k7KfewOzazHjvHpBfSouxRQtS02Q/UcDwPVDQOiIUwT0m4E285yH/aHkMzwGko=,iv:kkbSnbxpH9BefbWD6oyKo8eFVDNt4KDvKxqUHW+QjR0=,tag:6k3Zq0zt5GKz1A1bADZhAA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
