apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:+wEo4HqkMQNTvA==,iv:grcretimhQz3VylJnWkUPRHp/QbDD9ZdWGB8GPKYmtc=,tag:pHitornP4enn1DgPemWJ4Q==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:jth3t1WeuYQ121JP3kxDHQlN9HDdahNLqigFijaDw3lGqFY3PVWY5g==,iv:EkLWfXbJrBGQs1MjphsGQHFnB7pLYVkNK/B6If7Uyys=,tag:PprviYg1rmUxX4r5IWA1ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTjU3WU1WS1NNSTkyL0dM
            QkFWQ1UzUzlRU2dxTkVVWkIzcktIcU4zUjA4CjMvcUgwRDg0VWdmUzJVVHdlZE9i
            TWY0TTRxVEhodk56WHhPVW56TXBhNEUKLS0tIHpKeEdQQUFKRXRLV0RrelljS3RH
            bGpGbFRGSzlMbkJCeElkNUg0UHlGZHMK0CMGNwSYr6d5/7akvlw4Vbp/249n6jtn
            Gj/kHTJRDnrdtX8pane5mp1H8WiYXes2yPzsEr3gr48hYtXiSmLYEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T08:11:19Z"
    mac: ENC[AES256_GCM,data:WA5SS5+3Yi1GKJJ5IuQ3OCDDCxtVivqR1ia/CtknOX6au68LOnpWfE1fJlTFmqiikdPGLlRg5Q9P5n5mpUpMgTjWVN4h81tY4sDldvMSZMd9U9IPmO/rnMBphuHR5aWPZZc3J1s3VmmzHSeS1w38MdyDEG1k7Iz3fnsr0UwEXI0=,iv:Bxj2agSDKQdDLZ5ZGjWPD2rgtmi181IXhzlT1LVF/74=,tag:vAKVYBlRboCgQz332pqGAQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
