apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:bYxTr1B9SbjvRw==,iv:nUhphkdZS8x6kvqABgcNm7UzQKKUPxeaGKskqMaTVXs=,tag:nhQlyYK+mguiGVIy3rDHzQ==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:g34/jxNa0bY4atYeOI9IUtHZ9ND4xw4vNWPKJKUxWY16wKgObOFGiA==,iv:sN+MiwYl3K7W/PwzIO9fQD7NY2JCwQnW+7JM0co8fvc=,tag:eW7euIkuYU6Kc4nXZoU5Ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS2ZWeGZBTHBWNEljQlRP
            MktBZms5bGxPTXFzeXpTcGY0U1JReXZCdDJzCklOZDFWaFBlbm5KYjdZbU83SVpi
            QmExUWFuM3lTVkRMK1Z1QjBYRjJxTFEKLS0tIGVHR3JWMlh2YmZBTkltUmZ2ODAw
            SmZBZGNLZHExVFc5aTV1YVpEU0FiV2cK3cz7KoGWgpRRGouufXZtssW9UNgzgEBT
            riu1se4zCGwZqnXuMbQeZzuUeFXp6My2hj3o8RfbLQP1Zr2ZSHVgkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T07:54:58Z"
    mac: ENC[AES256_GCM,data:vIdGk8wbZ4xxjas4P3HDN3G5sHp/5jeB7a26s0VuUa4wKJRMF3OyHUqouoTnkD7SYDSVbKOCcg3lAmncJO4Ik0tAKbZPXRyV0VVhzQUOCjCWhs9Jx77rxDruPtBEXG4YoJtaPCcNNoY7HbA7N/3uMiEApwtYnUGhHgYCsz+y8Ps=,iv:HJPNjEcdnjej3Lac7ZSdrjtG7YONrClYGS7d+FQdxtM=,tag:IE4Jtp5xH2oiR8ehujLwew==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
