apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: minio
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:8D/MBTTZcIwAMoXN,iv:Mex5qTQOFUcYLfTF10CiadJdXkqp797VBZng1l+ZySE=,tag:RibE01TzpExX51gmJs87BQ==,type:str]
          stringData:
            clientId: ENC[AES256_GCM,data:uQuDisuy2yPcwCGbssaB3gYp8RbLR+WhfV9sUO0u1U/OEFy2DjLs7A==,iv:bASTBNhjOKU9mO5B8YAPY05ZY6L3IGdhVusLDwpUZAQ=,tag:Ybn+LCJLFIph8PG85JToHw==,type:str]
            clientSecret: ENC[AES256_GCM,data:JlP9cXXpJFOQglwvm/f+HG9sXckklQzd0VA15sdPloK9bYDRjRdAJY/5dj6uAKI4JI13nZDSoiw577R2PLKC+0eoixi3eNpV2itsIzU4fRiP0My0stK17kZWWoDkRtolC9fBH3hoCOw0TM2fRDonfUsp4hjrV7vsKFwvJP/+GdA=,iv:feB36OH1XXxEtWZ4Cww99cQ8HW7zxiDtggZe/8Lxdy4=,tag:aHizOKk/TZ7n355qTFlZYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUTI2Qm9EYVN4bklDZFpy
            L3puaWRzS29HbE5ZaE5OVGdzVFIzb1R2bVNvCjJhYzJoeXVuNHoyK3k1YkxmaU5S
            RHlFQjdXU1VJSzNJZ1hxay83S3N5MDQKLS0tIDFTWWZhMHdXSTFwTWhFUjRJUjNI
            RFlPSGZnT0xmanhWa1FnaDNONmRLUWcKmbhaFBqOb/Q0y539g8wcPh8tLVtJQIwW
            OtQkVPMk+K/KDxb8udCx508tUAM+LkEjXOaWF4Tpn8UrUo+Whqk2Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:Dob8Y8+jwGUTRq0tVgCBAJQ3AjNYfFJNLpIT8ujgBUDPM4m4Uk8QDmMTGGUP/T5Z8eQHI3oyRloarCl+yBAdnmhkStShwyKTiFXUGGBTFApo+yVFyTr+K6Khj0SRte/x7nPAFwj/RjPtpZs351NOVhVhcgoEgfVx1Qk9XyGdbpI=,iv:WkU2nPdjl/5/B+G6vtpKtNSLP/JwM7/k11RYmkNmPfk=,tag:MXJZXxBs6C54YuLQRGNChg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
