apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: minio
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:/wRpvEDUN+gAELzw,iv:wkxRE92LRnRmk+B0j3QCjhAevaRBiSe26fhpzpWxfgA=,tag:W7QBNNeht0B4Zk13tf16nQ==,type:str]
          stringData:
            clientId: ENC[AES256_GCM,data:EQinoweIpMGkajWkyziV4m2KIdyLZTGCj29ahjKzqgRcfGD7Lv8XPw==,iv:WAJVaqSP0j9fE3AqIf5kKg4BqTuCSk2R+XyEETf/Jqw=,tag:kxSTs8Pga1WaWYEki7k2dw==,type:str]
            clientSecret: ENC[AES256_GCM,data:qDmx+SHJ/va84BBJ1kbnpEyvP3a/MXbe6mc4sQv/FdTWruwCoPNWWxumzV/FfG34nrXeP8zhMOYNyYeanHKBDM9owWqcjhkg8jhK27BkdM/NPJrK00lFrHIsLqehmEFL/pEGFyKt/DLFdQaCnEtMUeq07c6SG9ihBMgMfHw9IQs=,iv:di+qhmVCLu5KwwB2hmtvAFXDZResjHfehC/LldoBjeI=,tag:poSdyJOU5KLr8AjukJKSeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTmdRampSOWJBUEp5QlVZ
            OWJEczJHOTBHSTRGMHFWaTZXUVBsZHBEZjFRCjQwMHpnczA1TWxod1VFUGxrQ2Ez
            V25JQUhZOXVZM1laeCs2dWQ2K3g5S00KLS0tIE9mbTJhSWhpOHBBa2RmT3F6MWRs
            djljWStSMTU2WEVhVVpOQVZBZkhiOEkK87K9SP5vr+7Uro/IL1+s40/ztY7ifmbH
            sy/8n4y0btMLgSpfS0Fm+8iAR4dDW4uu+UGRjrHRoOuNSUv+tH0cQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T08:16:19Z"
    mac: ENC[AES256_GCM,data:KbehijRxO1M8S1SYBCJfIA13AkbBhu2S1N28k1diafJlKUbm31XxsYlsTXH4Q183PPlU3Tdf/PoA6yOIlAtU0tdjoGpopOpqOtssbXeHMQG6JoTP3ExBVGSfzABxjFtLJgOB+JiAptdEElEbcBl1+wlHtnnWAm1+2XiVXI2zAyw=,iv:ohgbsHCsOO9QJzGGy80Hopmy7LM7dXB+D6/Qrutk+3A=,tag:UtSHlXE791Ul80VDj8EGsQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
