apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: influx-secret
    namespace: influx
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:9usqLZ6sN/q8FJR1KQ==,iv:PTvF9NKKOrIc1SHOGhC6j5X4FNVAuk8lI2XKvVX5FMw=,tag:gllnUmWxVH60qemgfjvxVQ==,type:str]
          stringData:
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:i5HgjOdgFBZO82NNdE6H9MxkX64=,iv:+w26j0BJm/d5wlnHDBzt7AI3yewEdDWDP9So9VrUB8U=,tag:yu3W+WwdYpUFQAuzxBoAGQ==,type:str]
            DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:kex5pBj3d0DmaTFbecHeWzHgqZE=,iv:/k6VWTsiwoDA5LhSm9J1TcUjeos1vioZnYB7c8lIWpA=,tag:oGOF+93A9m7iyTznk/GcCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UXVRYmo1cTVkYnllRVha
            WFZlcHV3SGl1WitaNUhJbDdKRmFEWVEzRndZCkJET2pXRG9GRU9ucThKT0V4QXl2
            cGdwN2RzdkhyNUs4ZUNBTTBoSFNkM00KLS0tIGdBai83SVJvUEVwUDNGdUkycXFy
            SGpTTW4rdzZmMjBab1NVRTVRWG1OUk0K9UPyr4lP2qts1PjU0V+gfw4nNu+dLfWi
            3b0VIAihpGSByzh5LqlJ77e1aO8ou/4gMFoPou6O6JO9mjeQ7PMOXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:yTuYwLhKevmN3DiqEwevLZAuG2IDAJbkfgdtj+o3rmWjDMpztQQjGkNW1I5w5dTmG8xevD8yQTjCHLC9TEHFBlqVpdyzGjjpdeiqleQ6qkMNuWJyjoH11H8oLmw1B0NLXRyPoJcQNrig1eCepo7QQcLH2vGA9vtrwwgl2xp71Rw=,iv:agEgK4EQMsVIbVcwy8Dzwo4KoiIw5T305uQUFwCYDQk=,tag:w1gPZOaFphkig/JXA1zlKQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
