apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:6+ef914Ilhb9nw==,iv:ph7adg1RpIjYIaf1A2guLy1kerwhfWk2uFibpA9VM/E=,tag:ODUiU3UvDJLDF3RPy1oE4Q==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:gCartx1yijqOdXQ1c4MLgJgS4P8UJIi5PKHD1q4J3ByEoyhMGqoikA==,iv:3ZzER37FsR5BfduwOfung6Hhit2b2BEiEDSRYjk/yjo=,tag:RkvyjIMwQVIkwgl48rIJ7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbGVGbEdTdzNwTzQ3bmZJ
            RFRtZUY1K1NjWWRsekcrOGdNVzErd2F0L3lvCmYvY1FwMGk5VmxMYklwbTRaODRJ
            dGVtdnlYQldoWHNpdExHRE9jbzZUS2sKLS0tIDUvMC9RejZMeGVWVEQrM2l5bUN4
            UEpod1pwUk5zeHBTa29vUVh4UDlVckEKUz5Bba6Eo879dhlwt6oA9wE1Hoh0FvxU
            ciLFWjLhdgezu8SPcKzoWA9gGwuQZnMVaugDaNgfk+nCcMHOhUyiqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:+oBFAwnUkJK8tnPHOV3a74/envGlIOD82dV0bfcSdVZ1YqDBJ0STjw7FT7SaX7DUXBe/IE6RRevL9Zr1SWk5WvQ3lxAsWupKU19njpXVPLsmxb/6W/X2h/TY5HKSU4sKhTEISmdva0bw6bKe+/pAhvR+qghyy+ttXPzp7tL05JI=,iv:KMukeCVNBkr+BnGMtA4wwLk9/okh5azTGKJ1mnqBrlI=,tag:xDcS7y8YOZkxurrit9clhA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
