apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: registry
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:qiHw/dBFftMS6uk1,iv:ccsSvQ1ZX9XewjXlqisPn8SC1JK620LcLD4vGtGWKsk=,tag:eyjhgu2c9nRkdzgDSWLJag==,type:str]
          stringData:
            REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:V47CLUkGTby8wAJyMUZE14JEv2w=,iv:K5D8FABVuEuEkEXk31k0W4q4hgL0CdbmQUn3MAGSr8M=,tag:7PHjoC3Y/ru10XftcgJWgA==,type:str]
            REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:ZmpORF6rG2QquKdcocxk/s5/f2xRsYPM+4fOpV0BZLRUhNJ2SuQc9g==,iv:zRM2EKSna2WmHupgk27oagRWQss39caeXRBudZ8WwAc=,tag:K1nQb3d4h05m/I9k7eyk0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN1pFQVVFS25Cdm00STlX
            d0gyRFBseWNZbytQZERsU2RaNTNKbTIwUEJJCjN1bGJSUnhqRFZXN1hVMWcyZ0pS
            RC9NT0lFWVZHc01LRFQzcWwzaDF0TkUKLS0tIGFOUW9lOTJjMjlmM0lXU0U2VzhC
            Nm5PeFhaSTBZSm9oSWdqUU5DbzVHY1kKSODQ2zMsSWgA5j/d11lS7S7fpAOlFZjt
            6kunDlItpjhJOKtyhzk0aidQ47wibvqdY0DMO1lzM5jDE7agIy6ZSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T21:47:14Z"
    mac: ENC[AES256_GCM,data:XQK09tIfpb2T2n5Dib3+xDu3p8tUsGhi5hzLqdeGlgz0Arj6vcz+OoJV/0o2HeZrSfr7/CB9nGTk1qNRDyxyh+DPP50GUyuhbLfUYDrvb/yik1PPpXa57hcllAvunOuzp7UUfLfMTkFOLNeX8UMjBIfIYHMqx+1u1PdLs6L74M4=,iv:pKlmSqQcQ8dHW84Bs6o5myy2EH5tuvlxar/ITmlMPFQ=,tag:B+u+QmnrhQShe9xnNdPfVw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
