apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-secret
    namespace: grafana
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:Bv4Gmxw5tKDuPr3m56zTv/Fx0SO+vyySJA==,iv:Ek6XUWyREbB/UI8T/3qwP3szIARl1+kkcGsQ7dX/rRY=,tag:wHQdkhyPWH8KfBZJWZ6ZYw==,type:str]
          stringData:
            client_id: ENC[AES256_GCM,data:0f2owWPTv4QnmCXxPvbTw8jU6dpMfneN2eSTMcdKlQAxwwVENnS8Rw==,iv:x+KqRDdwBWg9OyIc14zJgQnevuixbo1k5KwjUbD5rLU=,tag:dIU6r+wC8nuvbGe+kg8ZWg==,type:str]
            client_secret: ENC[AES256_GCM,data:pmZJ7v+3dtvWNN9FX8zm9gWnYwollSpjCrH6fCdTCNpCQbw9Hgx2Mk7lOuWBdhaEKokaFxuHVMzadyEEWd6jG13fkO3E6jbZ8CSgAwmk4TSVoNCYr8Xf3ArOdS427we1a5ZbX4KtoHG+01HmEQNB8F0TeTQtiD2RYjCu1T6Ejs8=,iv:pMrUwvsHH4oFiDnoXsFAZw9fLaxNJnlq2/HTqmvjRsY=,tag:/RtMofrHSWbhudQN0O8TpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWXZyWHBzekpHMW9zcmZk
            dytPY3luRi9QT25vWW1hVXF6VnowVlJtaFEwCmJMSWFMOWtwbjJRWkF6LytlSUk4
            MXNUS1o0anQ5aktGTHVyMUxaQmFlWlUKLS0tIEZieG9Vb0lSZktsOGxURjdhK2d3
            NTdUWnJFN0tOUXFJQ3dsWkdPNGhoeTAKzoQywBtmhezWDDoy2xwLNEL8U6ceUVWO
            kpOt6AMKb7lNV9TMf45LDQZli2GBNTHk+BYvOn0EJad5P9oOAVdYMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:9s4CKoorx5JwTzgan8BELQDgfZaZq1y8JzbciXpbyfl8Odx48nb0xe6IDPMwHa007yH1sJoyNC2zGDgZk4jWnalFRJyddJNG1LkrkAzaEqYG+ie4abjCz4D7xU12nTOVp2CRv6ZVioI3AXBiAr/nOsmrvlckrlNl38OF3LRbUv8=,iv:Si3ILOELX7DcnMPb1EB/yjDkMO3HaONrpNf9XKay2hQ=,tag:9QiPtS4SeovTAIO9bL1d9Q==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
