apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: registry
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:tWVnTZupckNYb7AZ,iv:/fLDX/QXN8lRN3a2BAIypNsktmUaN41TjPxfMfJ+CXc=,tag:0GB4gWcA2NthaELmJlyasA==,type:str]
          stringData:
            REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:6spVvCb11nq4ndY1MTJiRlxhfsU=,iv:P4TyWuYPhLYuRXC31YXDYj0L5oH7OwqGMt/6xvRT4z8=,tag:hR/kPcTjjhCVkAgPpFwWlg==,type:str]
            REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:kLDZQLQdfPaxck1MUzbPbDGEpfuJ+mJ598rSzFuNWfx0ngc7ph5cAw==,iv:JfNevp6ikYdMrm08cWxI1IsrQnAhXAvUtsRd7LAn8OU=,tag:gz4zdi0zmvWc16DxLkedsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TDhEYWlsbEx5R1FPc0JD
            ZjFhYWo1aG43aXphMmFYYitZdG95VW8wbkdNClZFWTI2SU9oUExwWldEOGhVVHdw
            a0lnOEZzc2JVU21paXlkRTlWcW5YZmcKLS0tIExBc0h0RVl5SkhNM1Y5NkFkUTM0
            bWlVanhjQmJBeHhzZm16bFBYUjkwaDQKOJS9tRqqH6lz6IngLjwjUYb7OYRwHIzA
            ozp/e8V6n3siT6voMSjzynCvEXRyyAiW5I4zxPvU1E7RK8FXFFrYmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T06:42:47Z"
    mac: ENC[AES256_GCM,data:PXa8dEtpSez/r/9Kn3mbJNfCuoSTzi4xbtW2Wo7Q5TVS45yOyQ00P2k99FBsHTE6PR8lrWTWuWYQK/6ZMNbewOwFj0y611iH9gHmanAe62dxy1pOHnaI8t66fQQw2R3GeO+PQC6diDsTITwZEm7BQJ9cXtt3o9qPnFOnW02vjGQ=,iv:UAqzKwstvtn6NcuxTco452ZxabI6KEVDcpFrQ2ciFek=,tag:SGts7O9LLW3KpRsMEWDVZA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
