apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: webui-secret
    namespace: webui
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:pOzhQAw5t92TYkCf,iv:+Sg/21zPvpdCg77LXwFWbw493b74GAaUCxadNX2tWYE=,tag:gdCBslEKnztUpBKpNm5zWA==,type:str]
          stringData:
            OAUTH_CLIENT_ID: ENC[AES256_GCM,data:0oKNZw3J22ha2fSFi6YCGgnjYLR0mX4b4c2asZ8T+qPSYmB8pupoWg==,iv:kJHIFQ0zYmUgN0SUfMfvt+askHXoWTuMm9RwkouW1S0=,tag:MwazRkikOn6olMkB8ny7NQ==,type:str]
            OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PT6qLFmyphgGm1Aq774y/KcRQsZ0st5ylFIvSFbNFVUuBOHM+c8fcqli3nlYNSWeKBsPXyh6Py9qNNppDSRpV3RX56n16/ftFjX6L1IfMdlnKi1N0PEdzfwUsTMAaptICAL5fNwr0DvFQaJjwhdFD2wn9dsi2essH+etjsSVQPY=,iv:DuS9LdIdu24gGH0IZ4if1Y2LY9N8Tzs7KO9sfZXcaLk=,tag:Ybuwz2aepj6PYuZcLBa5+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXFzb2lCNG1hQ0I1TkdS
            cUhoYnEwODU0Wmg5Y05Nd3YyNkFBaXZCWkNFCmlSQUFjMlAvZUlVNVpPc2p6VmpE
            dFhzQkxWL20zUXRHRFhIdTdDcVA5UE0KLS0tIEJQcWFtYko3ZW9XcUlWdEloRmJC
            SzNWWHg5Q2Z5bm5nS1h1UittMDdMSFEKvZpZgsZyw3Hbs0au+UEBNpySnsi0GPhb
            pcU/HNDrndyLehfacQa3TqPdj4HWfZw6dsMwYMDyRvrstjcWueN6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T16:56:32Z"
    mac: ENC[AES256_GCM,data:o4fKv1Al/zagPtfWjVIyzlrwne0G+iRF2rvck67N/6tI8hQs30ajJgHwTyAxD8+XQbBzD00CqkyI2WMWq+atk3BG2VcfAFbDXi+k8SvEA0E+bFjelqOkKTP4eGw29YaBGVFceEBtREci6vALAvVlBvIh0BUAvV5ye3qLANykEVE=,iv:7YcVYaIdA7o87sZROs24CXgV9KqDaY1igiYcw6SAI9k=,tag:/JBkpbbQsSQBB309ZPh2pg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
