apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-workflows-minio
    namespace: argo-workflows
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:Zre0ZUbzlEWrrLai40KX9gf1qyo=,iv:6EKaS6FA5yrsWQXoYkguCfb3IwPZNzPou43JAlUSLAE=,tag:G89lFYN9qn/SKJ+eAdpHiA==,type:str]
          stringData:
            accesskey: ENC[AES256_GCM,data:vxETcjLpc0CCAm8oZODVzc39CpM=,iv:LdO0VjeHAnDxRFVuyAu7P1mBf+DvmU24c72lb+CnijA=,tag:DrjXIqq09DTmQOo5D9HazQ==,type:str]
            secretkey: ENC[AES256_GCM,data:jbkMa7lKSexHFU+Go8ncq4u2bTmgYoQItLB6ufCZA3LpkUOMqVgGWA==,iv:tO4LyMc9U636XJQGybGCsEEPh76NkuukkTcZYjGE+X4=,tag:bl/rmVw7NfQVIwubjYmhZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVG96dFVyRnFicFZ0NnZj
            bkhBdlVidG5OTlkrdkJwcXoxNzg2R0ZSNDFNCmI3TFUxbkJpQkVXQ3JObU1jNlQy
            U2VockhOMlliSDBpSXptbzNFSzRHTUEKLS0tIFpSS0dXK0gvV0JoeFNxRm1lSExF
            RnpRcWxxRVJOYlZhQmdwVGJnd0lXQ1UKZulez2cY2LwIJw7UErzHBp85pGQWxelO
            4XfvFW+vyNQEw8qsvQ81iXewP95yVn65Q+5mx6L9pZMYJr22HxMNJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:VkNgl+5ejZ+YwEHT6JZhNMQd5uMxv+vYo+rA2KLAFT+rUlCLCSMoGVGz21FBZtUYGR6gPZ39HEVq6EbRMve2bznhPsxsVOUZnQcw8V0vU6RV79389R4ft3diGsHKAfZTHCy17X/e6L++KwmS/cEQADVnqgKCdyx0PTpapc2p0bQ=,iv:OgIL6fLFl/M/lrhntsRBsREGLWkHkV4QVWX7TlDfpBM=,tag:/nPmcWTVCD9oxU1VnzNooA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
