apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: woodpecker
    namespace: woodpecker
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:/5vZtfyhzx64SNYaw2vQQQNZSbIRmk5Q,iv:XpLw5WcyPWvdg38OfHkUhTDg/vsLsMg7aZ3VX8OxdSA=,tag:PEt/qD31T+asKM9JySz3iQ==,type:str]
          stringData:
            WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:0hBZezxSyGRKz7uKsF0ivj63ZxE=,iv:FQi44iYIR2D+eH83PnyzSt1BPbRc5vZrvrNbllY+AJs=,tag:dMIjkwTF2IFIHNobDrrtDQ==,type:str]
            WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:7kanWjSqXko+hbPk/ejK2KF636zHIxfBJgsIX4ycH+zg6qd8fqWStA==,iv:ewIFAd4qrA2X02X36sIDRpAfcUYuJbr3i8Og+U/jFYY=,tag:2l9ZWW+21QV8otMLvyHeYQ==,type:str]
        - name: ENC[AES256_GCM,data:g94gnlcUXmM+DlwyhliFCA==,iv:UFDaNYXEpsY9hKgwP9blx8eKxQWFBxDW9Xrd3y0YV94=,tag:/ct7W+YAb29pvSOd6Kyo0g==,type:str]
          stringData:
            WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:vJTeg+oTzc2+K80w39NFmAr2dHHmKOetprhlIcKdirqFNn/bNcvAwIvKDnGYOlmnabYxOgP2dAbPsxoPb7ufRw==,iv:xQzJzzL3J9kDX2beDpqBqxJZ87Pv36Y0tLBx0hm/N50=,tag:zvYu+uvQgHAe0UD2TBa/CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTW55RDFHQnBsNkNqaWNY
            Kzd6TnhRZ24vaW5jekNOVVp5MHAwSmRWS1JvCndMZVg0SW14aXVJUngrck1kY21H
            V3RkL0tFK052Y2tiL2x0Mms4dDhoRDQKLS0tIDVjWkVXb3lzVnMwaWpHRGtxN0ZY
            SmJ1VlVLUkRyblhPWEl0QnlWTHFPZG8KCYnTrneLMhVwUQAJeCH7Q/FmK1tqByMO
            0+i4SjLMvMCN85MHl2wmSl1FmWpgNO6xfvf1eFd5fgijdX3AVpxFPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:02HYTSv+jhvYYDRTShncGUjBjqp8k2L6FktNdp19eBoJfTtGmEH4GvtPX5EL41fDA9JF3asZYu49AGMPgQ7NxtOUo9Czib0xcWEYq525uEjk9yrw2+h1bL7a6+l3dYb90RSl024hc+lxqLBFb9LFyWDzyuf4LzAXkMB+m1+3RRI=,iv:/2PT+yQq0S8PW37BtJVf/eG/Uo3Zj5eFc/yOTrfP9mE=,tag:8diMlffWLKhrIwpH8ka9lg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
