apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: registry
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:Tyze5Aj7VTm0+nv4,iv:P2e5IYAYcCMb29nLTm/aM4sdO7wsbr6sAz0KMVYhpTU=,tag:uu9QzMQ9/KF0iUeK1ZaqWA==,type:str]
          stringData:
            REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:OlwRvBNsd0RdwBVT9c0yd80UCRQ=,iv:+sEeCjksqEYAJOl7Mo9me34D0RW+b2zz6fjZdvCCI30=,tag:xSOW5anuB5h0dVX5caHjQw==,type:str]
            REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:D2FVqCtHK2bXkBhu+xRHppEjbToq3SegDuInDxl8VtbA5rmpO+A7qg==,iv:6uYf8MbNX5aeNJHAOHkwJJag5ap1mvVprhtbF6ri4w4=,tag:dUjAXdDPGjw5Niybn5z88g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdXhNT01ZVGNHeFdRSS9u
            L1ZwdDF0RjVWenZNSk5CTHV3VmFiMlR1VEZvCnhLODBnZ1ArL0RBY0d3R3BtTzg0
            K0hycmNua21tQkg2UVJWRHN5RVdYTWMKLS0tIGR1WFc2T3dWcHM0R3BGM0YxMkpT
            b3I5bk5mVHFrbmZSK3VYNVdib0lLT2MKF10fAQgyZ3Vc7NMlV1kNbhmUr6V0eImw
            bMFPDoUAodwIJeAlh6cVO+ub79ZT7U5gW0cQ4mqsVRXsNX8pJeDX0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T16:56:32Z"
    mac: ENC[AES256_GCM,data:kCpYrIqfWhFvZ96mCgklWlR/3Z3S+bNIzsQCVbFCfeLvaDFf3CDP6Vaeu2tH6Y1nbXB1y3nmQOSUefyuxHseMtHOHExfBK1rHgdYbyJeX6VLkBilhgpdE4RBvPyq7BFTcWHg0u53N2LlGWooBJKhXiZuvTJxKfU+/Yqe/YJGRFI=,iv:/7shxfZuUVofP/VKMq5GxIRWi1HwF/U/VV0XtKc3jbY=,tag:DdwK9ckiPPtaSKrP/bohTw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
