apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: woodpecker
    namespace: woodpecker
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:msMNCsXREjs/qWIWAn+foj1AEgXfQoGI,iv:56ekiGJrYGBwEG34PiIJSeAZerae3KuHWBiCuzD5Ego=,tag:hiKqy0+gv+ev8hWwLRAsig==,type:str]
          stringData:
            WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:cK29JuMiDaeSWhpWFJmdihxi44I=,iv:tKZjUGV+o1LSwdhF1v/rYrXqAEbE38r0lq1RSUHd+Lc=,tag:Hkjs9gDf2w5Gks+M/qDe3w==,type:str]
            WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:2D7CaD3AyjoGsuFQckoq2VSrMTSheyLUfMLBGWpvsG49IW9jPsoeKA==,iv:Rq68JVM19VTugW3hHqR+086f6yxWeTnoCwyIOEeoHQs=,tag:qjncSt/aiDi8X52HPfF6hw==,type:str]
        - name: ENC[AES256_GCM,data:eiTGKUXKV0tywF/Abs07pQ==,iv:zmDL8uGCc640B2vCRKorAkNdFaQpJA0jVpdMi1ENZl8=,tag:6IGENFft1ArG4nWGlm4ZQA==,type:str]
          stringData:
            WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:6ARecokAB1IWZq1fHVSlN/P+u4zPTGjtOcR8nKsQNRHsOn+JsubJ3YCyWDohYTeBVyqlEgo/CRTAjwWrlGqbTg==,iv:k7yJ6eJkUHxS33lOHzIAl2X/ai3TT0XLgZgcPSt4jwc=,tag:hCO1ljgoftVLb+UkFW+y/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQndHVS9kZHk2bWdSUDcx
            aTZlVkh3eUFQSUk3VHBSZHQzallqaDQzL2pnCndpL3d6T3RVSFpCRS9Pa2FpRUFQ
            UGRzNmdxc1JuOWpBd3dVMWUwaGtpSU0KLS0tIG03clU1TVFtL28yK2xBaUlCMG9u
            U3BYNEc1NnVvVDRtcHB5MzJzQ21MTDgKHg6N3ETVMq7IbabPaO4HysGKSh1SZBOR
            Sbj+3ST6l3+Cn9ImPBRRPNPb70VFzHALnfu6aGPf/mrnlkIaLxeJng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T17:15:57Z"
    mac: ENC[AES256_GCM,data:rAay+/SwdtuDPJk2/tx27+k+52TBJUxnQrb38+jEIKZwxg3rIWL0Z25WU/+JveARDDMdADHzAXMiwDB5OV1QVsJnPnwjilJk77rhw7T/1o9fWSSfdLtFEa6N9zGHfDStv1dnzbTBtA1013q2ipkwDwWr7O3aq7M+Iqxj2pMVGWo=,iv:ojscR8m6lUZ2tpQieoxqqycHIhnIJzRCwnAiR21lKww=,tag:IhL8Z7Gl0F69hyK39cT+bw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
