apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: influx-secret
    namespace: influx
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:EfNvhIx9EJQArUeT/w==,iv:UXrgk5JJBPkohBbGR3eGO2Bki1QCQeO4F/6SM54/G5s=,tag:apNnQusb7135HKSzXB5BVA==,type:str]
          stringData:
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:AfjYNAGYgESwcuTcjlzGdeFTuBc=,iv:bIT+b6G62zNqlmHHQzhcBKE4Ws7WKDVEcQQbwzpb7rM=,tag:q/ON88ClndQc1my6qUUhAw==,type:str]
            DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:/f+QEbX3UH6R7M0QE+znUdiug+U=,iv:mzXWb8BMEMc1YPaHUOqvWSJ+Hm7sdkR/BK24DUbc0RU=,tag:WtrOVdx96MkEiMomhCkuQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByLzYxdXZiWVVRMXdEM0JJ
            ME5PbnljeENXQm1nc3dOWVk5ZURBVklpSUFRCnVoenpzUlc3RUZjSDVTd3RoQ1N2
            c2x5R3lyNUNidysycTdRVXZteUtic1UKLS0tIC8xeXFWTjc2ci9CWERBK1dkQTVp
            dkl1NTJzbnRocmFMNGUrL2RGK0c2R2sKbVuRBYfjCTOCWrqjuo52kQLjd+t1ko/K
            LAVHl2+CRcyLBIccU9CYZltg9ba8XLkc1iAzc3iaeE8kBx3b83ANww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T19:51:22Z"
    mac: ENC[AES256_GCM,data:X3675cT+LScCXGOfVhmb9FN3NxOgN8h1f5G33eBp1xsJIfcygBn811rpjUxavvmcg5sAxhzlc2DpJhr6dvCBCTlVTNlN8npjsDw4KdGu3xhNyhWP4d6G0dNNg/7si7wsXr35drSUjMhWxwtIGiFgyO1xbIJW/E+GbX9snEww8PA=,iv:XJOPVKtKONcwMNmKHIh+pOPpoNq0FwuVVHsSzFKrlWY=,tag:ZfW5ViiznTB3OfPb8Wa/3w==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.0
