apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-workflows-minio
    namespace: argo-workflows
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:IhhFd0q4drKA7Ow0SVN/MNmIc8s=,iv:+lqbLuRfyyDLve+5CoYV+q4e1W2wZR6bVo6Q4k5vxRM=,tag:We66TXNLGE4/+eZPwe3bGA==,type:str]
          stringData:
            accesskey: ENC[AES256_GCM,data:TvG6V+k+wPCFmM1qqCeW/FWUMvofKMTWxHP3qb3vDXrKVBNvDB9ahA==,iv:JFOWbE/zgcvLmzh36CUqRtZfMbxhunn1nOjKGM20cGA=,tag:1smndSAS6UyRsrHWIyZ9qg==,type:str]
            secretkey: ENC[AES256_GCM,data:V+OOy6ePvwJ8qPIRJsQu1jABU1nSntEAi6OqtzUXpBRwT5egwrxAmCO98EHoCErs5Z03B9lWFwsAY9htI/N/s5mGO8cNbOicYJUnUL41Jq7l49vtBJIIUKK0KSYpFThRjW3S+Qnk/9Ke4v0YKsL/17bC84R7euNFljgciKkIruE=,iv:b9UKZ+7v5/x8d8rnlCfTc97evTaVvxGrcgwIczIxbLk=,tag:k02ZXw6reMWu/fz9gX+8Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OVJIRjRIQ2toV3M5Smh1
            RzBjdmNwTDVBbkswWmZmWlNzWDhIckE3bEY4CkxKY0xGWVk2OGFMcGIreFhsVjlI
            Q1hvcU1yQXhNc1prbDhoZkZENkRkem8KLS0tIGQzSVJ1MmhiaUhZZGRQWTBzNFF2
            NmJQUmdQbnZ4OGROTkwrdDd4L3l2azgKwg/Uo0vCVvGo+1tlrbG56Xy77t0a1KAk
            OkdwMIxNVDatccYxqJNAGJ0GzCrDA4mW27i2OfmyJAV2+vQQXNSp1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T12:57:53Z"
    mac: ENC[AES256_GCM,data:Hj4CVuixZqqWDPfAuJgBUgxQm2UVQDlIRSoDz/fsYhgwavU3ELuPDBL+fROqwP5Fyvu+RzBDh1CWgo5rydKdIBSMC7pHRN2cw6JK7h3w61iwlU6yJsp5uL1q03lY85AKdWnyypYa1h6cPyC5aRBEBSrXhMUQ4IItmgAeka01fWQ=,iv:Fav7ZqENzvU2dbTLuvUe9Uk6ku/lbuAp+6/0y3D9LrY=,tag:jkZQkWK4s2sy6wosdGLfcw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.0
