apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-secret
    namespace: grafana
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:0TMs9yVU0V9JOS1i4nEr2GDlAmnuBNOpMQ==,iv:mIaW2PecWyGhn1FM2ue2p1utGx4eVRq5gYURTHy5WEA=,tag:gFjruOir4Nm44ZkMK9tYqw==,type:str]
          stringData:
            client_id: ENC[AES256_GCM,data:CYWi4ZT2m7b6lrQ6F5IaV8TSI/neTucPRWA6aMwldg9QyFq77xZOuw==,iv:vxwX4hicJWH5zETnQAwc/rdBgYRskA7GDmkZTCxkvOA=,tag:a6KbDOEwtj8iLCSQQjByAw==,type:str]
            client_secret: ENC[AES256_GCM,data:CxAmF1suxSpC16fcyw5KesrIdHvEe11NLjITJGT7ydSniNReZQkS0RFx3yapgiwhcK+L/Lv5Kfl6qib1LGS3e3hJ48KXJCRRKgwGqGu1bpnSZH0UwSI1Xyy4RkPZx2AilLPcLTcPk0z3EqCwdD/4XnQ0NtGRrhjYa2i3X0xcuK0=,iv:qhTvOQdUk4Gf3qj/mbB6vsX9WFeICJAObe2vrSJ3n2k=,tag:Mfd1sCUrRR7JyYBYAbbd9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZkJDQzl0VE9HM2k3ZGRX
            RVd5cEZhV2F2VFVWZ3NPWlQxN29hcmE1YW4wCkxieisxZUx4a1BGMmk0TnlTRG9i
            Q0E5V0p6U3UzdmhZbHd0WENjN2NRc1UKLS0tIFYydklxWGVaTksrQlA1bXhBZm5V
            Q0lXeWxBQzI1QnRpL1F5bnZiaWdGcFEKUgL9hK8+T0E+bXrWtnilKjQVZmW1DbNL
            ebs0A9HyJZaqGTBQaaFYFhq0js5Lc/yk+nDvgph2RBi+PYFEMPzsvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-13T19:12:59Z"
    mac: ENC[AES256_GCM,data:/qAhIRSJCBzkLvVR3k9mqFi1wB+uXmsw814f5qiEbeML4BcQvtFPnQoE4izwGgwjyE00NbltMG1vLmnXY4bi3d6o13nMFlo0R8lk1wYRS6sUm17jteGqyw0xxhuMmHHCmQeckPx0sgMjv9/7jhn3ULLKsYFi+83QeRYraXCBMoM=,iv:+xVXapMjR7Boxqi4Bxxb++Qow+PovPUSZcBGFXtw9qU=,tag:rFBFz98C+S2LYvuH/2KKqA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
