apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: webui-secret
    namespace: webui
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:DUSqtH084Zgc8QiX,iv:khZbW4qo0pypjG56qC0bJoR0EGNst0rgkXwAc1oPNLs=,tag:IRSI033QqdUVjvEd3Qi15w==,type:str]
          stringData:
            OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Ceg66bxxN7AcwbCTB/40+/CC4CJ+xsEYgmaQyHi5SmJMe54EdNvIvQ==,iv:a7kG2qAVz5i2ECO910BSyKkxHs7iZPw2XyzNcLfLpO8=,tag:0Yhk33fvD2N/T5AdXrnW2g==,type:str]
            OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:oC6zNCaBYEkDO++JjkD1WenosYw5/g9kX03iH7F0dOE8+6V3iw3j1FQ1T42Wt/dOq2pWblc3TMxsDd/hlTWZl0sRiiYZpBbhaHJ4ilHNmY2bzl/fuAvtX6WhYF8mEgkAHqAnKq5AGc5y3JMDtXBa2r/8gUJX2KlQI3hyD70nPn8=,iv:N2G6lMT7CrIk+/D7xWikTWsja1maqn1DcK6fZeXCfVk=,tag:NOUbFbFbRSf8Fp/1oLQS6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdC9HbFBEQ0N2d1RpTExB
            SzhaUDdhenk4aHZzMjVHM3h5V0JQWW8xbXlJCmVpRXlod1dOTThMMm5DOEc5WjRE
            UXloVFp6Si9aeHd4TXZ0Y0dFb1VGQ3cKLS0tIGlxczk0RktsdDNlK2N1ZmpIVm1K
            R1JWYkR4M3ZNNzM1YWFkSnhIaXMxR0kKMN69pMk7xeMikHth/Lv+niyGJO0qYHiM
            UBV+0XWST80vmMdN4NSvBA4R3gdxpjjF+F4e8IMUloGD8AkFObHRNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T08:16:19Z"
    mac: ENC[AES256_GCM,data:hwIuceHaocJthdmkbid64un1B6TP0llUn4SYyXh+JY4zbdRFACbb5l0JHLuDkJBN2BzW/VC9wZpBSrSPbgRqDwktqi3dxZzygXT+ohbVHsQvCv6kfbGehY8qEUqFef4WOo9eQ6TmhrEE8qGHu5TY6lfFtSXeHvYhXTvCyLuja3o=,iv:VktCOsYhrH8mvCvD/lO6pfOdvNG3Bzj+nSRyE5uRbRM=,tag:0gH+JG5PglswfQkzzZnEZQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
