apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-postgres-config
    namespace: argo-workflows
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:22PF4IXrtQEgMA0A81TUp9exWGg=,iv:3TDzbN+YsjbVWT7ELeB7JSxaWSX/wYqO1g3ayNBrm3A=,tag:WsIt8hNL9UEZKr0DQZ68jg==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:YSoTJGc/Xys=,iv:ho5qmYFVFH9ySiL0pw4dXWpRzoUNYjs5ODgwyjFxvnE=,tag:aEKD6mmH9l/0pLhWq8HyLw==,type:str]
            password: ENC[AES256_GCM,data:rr/cpvBVqHfsrwJ6Zdiw6fk8q0s=,iv:ZjAigW0TvvXsrWy/m0OMIe+7Sx17maglRqwKOH65fbM=,tag:5lnEEJEt3U9v5z6UU25NXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ255a2ZzMGJoekIrRUg1
            OG1QSGs1eDladlpNVm1HQXU0YysvSGJldFM0CmxlcHNjbEpEbDZPNTUvY0RaTThB
            cVNHRUQrcGtTUVUvck0reFpGbGEyV2sKLS0tIHdFb1F4QXVzYTRJTU4rWmNaWTVL
            R3E2NlJBanFqc0FsMmdvNXlCcTJ4ak0Kk6BzJX2TNGu25sGSp6DMr7rZkwtd15mo
            tVaEF/ih9yNqE4UbFjyhCxT9s8uDPSOP37N0coApKgQlhCrvLtemgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T12:56:43Z"
    mac: ENC[AES256_GCM,data:A2VFnX/6LKMMKl4mO7f2pZnGZb2ZZuc2AeOmsyspGTYckj4NOvXhzSM0/21JdQ3diZFxRM4vJx0LR9FKEj4GGThXy9rj+2UBphFLum4lKF/JjODgfmc9jIU4GBasWISJiUW2sTWersXRLCbwdgsWjltvzWRb/huqmunKQleFUYY=,iv:Ud6MwNjIqA91glVoREvLVuAIVvm66u+pybHNW9Lxh3U=,tag:wC7O6rUCtkeEf830gVFtZA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
