apiVersion: v1
kind: Namespace
metadata:
  name: gotify
---
apiVersion: v1
kind: Service
metadata:
  name: gotify-service
  namespace: gotify
spec:
  selector:
    app: gotify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify-deployment
  namespace: gotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: gotify/server:latest
          env:
            - name: GOTIFY_DEFAULTUSER_PASS
              value: "adminpassword" # Default password that needs to be changed
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/app/data"
              name: gotify-storage
      volumes:
        - name: gotify-storage
          nfs:
            server: 192.168.88.25
            path: "/mnt/data/k8s/gotify"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-ingress
  namespace: gotify
spec:
  ingressClassName: kong
  rules:
    - host: gotify.hnatekmar.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gotify-service
                port:
                  number: 80