apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: kong/ingress
    repoURL: https://charts.konghq.com
    targetRevision: 0.13.1
    helm:
      releaseName: ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong