apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  storageClassName: ""
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.88.25
    path: /mnt/data/k8s/minio
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: ollama-nfs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    chart: ollama
    repoURL: https://otwld.github.io/ollama-helm
    targetRevision: 5.2.0
    helm:
      releaseName: minio
      valueObject:
        oidc:
          enabled: true
          configUrl: https://authentik.hnatekmar.xyz/application/o/minio/.well-known/openid-configuration
          redirectUri:
        persistence:
          existingClaim: minio-pvc
        ingress:
          ingressClassName: kong
          enabled: true
          hosts:
            - minio.hnatekmar.xyz
        consoleIngress:
          ingressClassName: kong
          enabled: true
          hosts:
            - console-minio.hnatekmar.xyz
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
