apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner