apiVersion: v1
kind: Namespace
metadata:
  name: ollama
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    chart: ollama
    repoURL: https://otwld.github.io/ollama-helm
    targetRevision: 0.40.0
    helm:
      releaseName: ollama
      valuesObject:
        ollama:
          enabled: true
          gpu:
            type: 'nvidia'
            number: 2
    persistentVolume:
      enabled: true
      size: "250Gi"
      storageClass: "nfs-client"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncOptions:
    - CreateNamespace=true
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).

