apiVersion: v1
kind: Namespace
metadata:
  name: searxng
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
spec:
  project: default
  source:
    chart: searxng
    repoURL: https://charts.searxng.org
    targetRevision: 1.0.0
    helm:
      releaseName: searxng
      valuesObject:
        env:
          TZ: "Europe/Prague"
        ingress:
          main:
            enabled: true
            ingressClassName: kong
            hosts:
              - path: /
                pathType: Prefix
                host: serxng.internal.hnatekmar.xyz
  destination:
    server: "https://kubernetes.default.svc"
    namespace: searxng
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true