apiVersion: v1
kind: Namespace
metadata:
  name: stable-diffusion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion
  namespace: stable-diffusion
  labels:
    app: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      name: stable-diffusion
      namespace: stable-diffusion
      labels:
        app: stable-diffusion
    spec:
      runtimeClassName: "nvidia"
      volumes:
        - name: base
          nfs:
            server: 192.168.88.25
            path: /mnt/data/k8s/stable-diffusion
      containers:
        - name: stable-diffusion
          image: yanwk/comfyui-boot:latest
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /home/runner
              name: base
              subPath: checkpoints
          ports:
            - containerPort: 8188
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion
  namespace: stable-diffusion
spec:
  selector:
    app: stable-diffusion
  ports:
    - protocol: TCP
      port: 8188
      targetPort: 8188
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: stable-diffusion
  namespace: stable-diffusion
spec:
  ingressClassName: kong
  rules:
    - host: comfyui.hnatekmar.xyz
      http:
        paths:
          - backend:
              service:
                name: stable-diffusion
                port:
                  number: 8188
            pathType: Prefix
            path: /
