apiVersion: v1
kind: Namespace
metadata:
  name: stable-diffusion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion
  namespace: stable-diffusion
  labels:
    app: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      name: stable-diffusion
      namespace: stable-diffusion
      labels:
        app: stable-diffusion
    spec:
      runtimeClassName: "nvidia"
      volumes:
        - name: base
          nfs:
            server: 192.168.88.25
            path: /mnt/data/k8s/stable-diffusion
      containers:
        - name: stable-diffusion
          image: universonic/comfyui
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/comfyui/models/checkpoints
              name: base
              subPath: checkpoints
            - mountPath: /app/comfyui/output
              name: base
              subPath: output
            - mountPath: /app/comfyui/input
              name: base
              subPath: input
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion
  namespace: stable-diffusion
spec:
  selector:
    app: stable-diffusion
  ports:
    - protocol: TCP
      port: 8188
      targetPort: 8188
  type: ClusterIP
