apiVersion: v1
kind: Namespace
metadata:
  name: telegraf
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
spec:
  project: default
  source:
    chart: telegraf
    repoURL: https://helm.influxdata.com/
    targetRevision: 1.8.50
    helm:
      releaseName: telegraf-operator
      valuesObject:
        classes:
          data: |
            [[outputs.influxdb]]
            urls = ["http://influxdb.influxdb:8086"]
            [[inputs.linux_cpu]]
            [[inputs.disk]]
            [[inputs.diskio]]
            ignore_fs = ["devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
            [global_tags]
            hostname = "$HOSTNAME"
            nodename = "$NODENAME"
            type = "infra"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: telegraf
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.31.1
          command: ["telegraf", "--config", "/etc/telegraf/telegraf.conf"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/telegraf
            - name: data-volume
              mountPath: /var/lib/telegraf
      volumes:
        - name: config-volume
          configMap:
            name: telegraf-config
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: telegraf
data:
  telegraf.conf: |
    [[inputs.mem]]
    [[inputs.cpu]]
    [[inputs.disk]]
    [[inputs.net]]
    [[outputs.influxdb_v2]]
      urls = ["https://172.16.100.31:8086"]
      token = "my-super-secret-auth-token"
      organization = "homelab"
      bucket = "default"