apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://helm.irsigler.cloud

    targetRevision: 0.15.0
    helm:
      releaseName: uptime-kuma
      valuesObject:
        ingress:
          className: kong
          enabled: true
          hosts:
            - host: uptime-kuma.internal.hnatekmar.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific

  destination:
    server: "https://kubernetes.default.svc"
    namespace: nvidia-device-plugin
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
