when:
  - branch: main

steps:
  - name: renovate
    image: renovate/renovate:39.12.0
    environment:
      RENOVATE_GIT_AUTHOR: 'Renovate Bot <renovate@hnatekmar.xyz>'
      RENOVATE_PLATFORM: "github"
      LOG_LEVEL: debug
    secrets:
      - RENOVATE_TOKEN
    entrypoint:
      - docker-entrypoint.sh
      - Hnatekmar/kubernetes
    when:
      cron: "renovate"
  - name: build
    when:
      - event: push
        branch: main
    image: alpine:latest
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    commands:
      - apk add podman
      - podman login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD gitea.hnatekmar.xyz
      - podman build . -t gitea.hnatekmar.xyz/public/coder:cuda-12.0.0-base-ubuntu22.04
      - podman push gitea.hnatekmar.xyz/public/coder:cuda-12.0.0-base-ubuntu22.04
