when:
  - event: push
    branch: main

steps:
  - name: build
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: gitea.hnatekmar.xyz
      repo: public/coder
      tags: cuda-12.0.0-base-ubuntu22.04
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      context: coder
      dockerfile: nvidia.Dockerfile
      dry_run: false