steps:
  - name: renovate
    image: renovate/renovate:35.14.4
    environment:
      RENOVATE_GIT_AUTHOR: 'Renovate Bot <renovate@hnatekmar.xyz>'
      RENOVATE_PLATFORM: "github"
      LOG_LEVEL: debug
    secrets:
      - RENOVATE_TOKEN
    entrypoint:
      - docker-entrypoint.sh
      - Hnatekmar/kubernetes
    when:
      cron: "renovate"
  - name: build
    when:
      - event: push
        branch: main
    image: woodpeckerci/plugin-kaniko
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    settings:
      registry: gitea.hnatekmar.xyz
      repo: public/coder
      tags: cuda-12.0.0-base-ubuntu22.04
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      context: coder
      dockerfile: nvidia.Dockerfile
      dry_run: false