on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        env:
          RENOVATE_AUTODISCOVER: false
          RENOVATE_CONFIG_FILE: ./renovate-config.js
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ./renovate-config.js
