on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Validate Renovate Configuration with renovate-config-validator
        # You may pin to the exact commit or the version.
        # uses: suzuki-shunsuke/github-action-renovate-config-validator@36a15b83e37bf3221dc9c02ff5ffdaefb51ca1cf
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.0
          
      - name: Self-hosted Renovate
        uses: vidavidorra/github-action-renovate@v2.0.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
